NDefines.NAI.REGIMENTS_PER_GENERAL = 100000
NDefines.NAI.MIN_SHIPS_FOR_ADMIRAL = 10
NDefines.NAI.MIN_AI_ADMIRALS_WANTED = 1
NDefines.NAI.MAX_AI_ADMIRALS_WANTED_WARTIME = 1
NDefines.NAI.MAX_AI_ADMIRALS_WANTED_PEACETIME = 1
