-- NEngine = {
-- 	EVENT_PROCESS_OFFSET = 20 						-- Events are checked every X day per character or province (1 is ideal but CPU heavy)
-- 	TRIGGER_PROFILING_SAMPLING_RATE = 1000			-- Sampling rate for trigger profiling (Every nth call is recorded)
-- }
