-- NGovernment = {
-- 	SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 30 -- The age in years when an heir is selected if the government "has_harem" flag is set.

-- 	TRIBAL_ALLEGIANCE_HUMILIATE = 30.0 -- TA gained from doing Humiliate or Show Strength in a war.
-- 	GOVERNMENT_REFORM_BASE_COST = 100.0
-- 	GOVERNMENT_REFORM_COST_INCREASE = 40.0
-- 	GOVERNMENT_REFORM_YEARLY_BASE_PROGRESS = 10.0
-- 	GOVERNMENT_REFORM_HISTORIC_AUTONOMY = 0.25
-- 	GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 50.0
-- 	GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 50.0
-- 	CENTRALIZE_STATE_ADM_COST = 50
-- 	EXPAND_INFRASTRUCTURE_ADM_COST = 50
-- 	CENTRALIZE_STATE_STATE_COST_LIMIT = 10.0
-- 	CENTRALIZE_STATE_REDUCTION = 0.0
-- 	CENTRALIZE_STATE_YEARS = 5
-- 	DICTATORSHIP_TO_MONARCHY_REFORM_PENALTY = 4
-- 	NATIVE_REFORM_REFORM_PENALTY = 2
-- 	EXPAND_ADMIN_COST = 20.0
-- 	LEGACY_NATIVES_REFORM_REPUBLIC_SPONSOR = "oligarchic_republic"
-- 	LEGACY_NATIVES_REFORM_MONARCHY_SPONSOR = "despotic_monarchy"
-- 	LEGACY_NATIVES_REFORM_THEOCRACY_SPONSOR = "theocratic_government"
-- 	LEADER_AS_MONARCH_TRADITION = 30 -- How much tradition leaders will get when generated for
	
-- 	CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0.8
-- 	DEVASTATION_PER_DEV_STOLEN = 5
-- 	FREE_CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 1
-- 	FREE_CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0
-- }

