NDefines.NGraphics.LAND_UNIT_MOVEMENT_SPEED = 1

-- 	COPTIC_FADE_R = 0.55
-- 	COPTIC_FADE_G = 0.4
-- 	COPTIC_FADE_B = 0.4
-- 	SHIELD_GLOW_RANGE = 1.0						-- Set to 0 to disable Great Power shield glow set to 1 for epileptic seizure.
-- 	MIN_PROVINCES_FOR_NAME_ON_MAP = 2
-- 	MIN_PROVINCES_FOR_REGION = 4
-- 	RIVER_MEMORY_BUFFER = 250000					-- Increase this if you want to add more rivers to the game
-- 	PORT_SHIP_OFFSET = 2.0
-- 	SHIP_IN_PORT_SCALE = 0.25
-- 	CITY_SPRAWL_SHRINK_DISTANCE = 150.0 			-- Start shrinking at this distance
-- 	CITY_SPRAWL_DRAW_DISTANCE = 200.0 				-- Remove at this distance
-- 	CITY_SPRAWL_AMOUNT = 3.0 						-- Size of cities higher gives larger cities
-- 	CITY_SPRAWL_NUDGE_TAX_VALUE = 50 				-- Debug flag
-- 	CITY_SPRAWL_NUDGE_FORT_LEVEL = 4				-- 0: no fort 1-4: fort_15th-fort_18th
-- 	PROVINCE_NAME_DRAW_DISTANCE = 500.0 			-- Remove province names beyond this distance
-- 	DIRECTION_POINTER_DRAW_DISTANCE = 2700.0		-- Direction pointer arrow will not be drawn beyond this distance
-- 	DIRECTION_POINTER_INTERPOLATION_SPEED = 0.275	-- How fast the arrow is interpolating
-- 	DIRECTION_POINTER_SCREEN_AREA_MAX = 0.935 		-- The moment when the arrow snaps to the province (value is in DOT PRODUCT) 0.9-0.99
-- 	DIRECTION_POINTER_SCREEN_AREA_MIN = 0.910		-- The moment when the arrow starts getting closer to the target before it snaps.
-- 	DIRECTION_POINTER_SIZE_MIN = 0.9				-- Size of the arrow interpolated dependly on camera distance
-- 	DIRECTION_POINTER_SIZE_MAX = 10.0
-- 	DIRECTION_POINTER_GROUND_OFFSET = 5.0			-- Offset Y above the ground for arrow to point at
-- 	LIGHT_DIRECTION_X = -1.0
-- 	LIGHT_DIRECTION_Y = -1.0
-- 	LIGHT_DIRECTION_Z = 0.5
-- 	LIGHT_SHADOW_DIRECTION_X = -5.0
-- 	LIGHT_SHADOW_DIRECTION_Y = -8.0
-- 	LIGHT_SHADOW_DIRECTION_Z = 5.0
-- 	MILD_WINTER_VALUE = 90
-- 	NORMAL_WINTER_VALUE = 145
-- 	SEVERE_WINTER_VALUE = 255
-- 	BORDER_WIDTH = 1.5
-- 	TRADE_GOODS_ROTATE_SPEED = 0.2					-- Higher values gives a faster speed
-- 	TRADE_GOODS_SPEED = 0.02						-- Higher values gives a faster speed

-- 	NAVAL_UNIT_MOVEMENT_SPEED = 12
-- 	ARROW_MOVEMENT_SPEED = 2
-- 	DRAW_DETAILED_CUTOFF = 400
-- 	DRAW_BORDERS_CUTOFF	= 1600						-- Do not draw borders if the camera is above this height (currently unused in standard builds)
-- 	DRAW_MAP_NAMES_CUTOFF = 1600					-- Do not draw map names if the camera is above this height (currently unused in standard builds)
-- 	DRAW_TRADEROUTES_CUTOFF = 400
-- 	DRAW_TRADEROUTES_CUTOFF_TRADE_MAPMODE = 3000
-- 	EQUATOR_COORDINATE_Y = 671 --where the equator is on the map image
-- 	MIN_LATITUDE_FOR_MAP = -60.0 --the bottom of the map image is at THIS latitude
-- 	MAX_LATITUDE_FOR_MAP = 72.0 --the top of the map image is at THIS latitude
-- 	MIN_LONGITUDE_FOR_MAP = -180.0 --the left of the map image is at THIS longitude
-- 	MAX_LONGITUDE_FOR_MAP = 180.0 --the right of the map image is at THIS longitude
-- 	CARTESIAN_TO_HAVERSINE_DISTANCE_PROPORTION = 0.0 -- 0 = full Haversine calculation for province distances (so taking into account curvature of earth) 1.0 = full Cartesian (so as it used to be) in between interpolates between the two
-- 	UNIT_TURN_SPEED = 3
-- 	WATER_MAP_MODE_COLOR_R = 0.27
-- 	WATER_MAP_MODE_COLOR_G = 0.42
-- 	WATER_MAP_MODE_COLOR_B = 0.64
-- 	CAPITAL_INDICATOR_HEIGHT = 5.8
-- 	CAPITAL_INDICATOR_HEIGHT_SCALE = 140.0

-- 	BORDER_COLOR_SELECTION_R = 1.0
-- 	BORDER_COLOR_SELECTION_G = 0.8
-- 	BORDER_COLOR_SELECTION_B = 0.0
-- 	BORDER_COLOR_SELECTION_A = 1.0

-- 	BORDER_COLOR_CB_SELECT_R = 0.1
-- 	BORDER_COLOR_CB_SELECT_G = 0.8
-- 	BORDER_COLOR_CB_SELECT_B = 0.8
-- 	BORDER_COLOR_CB_SELECT_A = 1.0

-- 	BORDER_COLOR_WAR_TARGET_R = 1.0
-- 	BORDER_COLOR_WAR_TARGET_G = 0.4
-- 	BORDER_COLOR_WAR_TARGET_B = 0.0
-- 	BORDER_COLOR_WAR_TARGET_A = 1.0

-- 	BORDER_COLOR_WAR_R = 0.8
-- 	BORDER_COLOR_WAR_G = 0.0
-- 	BORDER_COLOR_WAR_B = 0.0
-- 	BORDER_COLOR_WAR_A = 0.8

-- 	BORDER_COLOR_CUSTOM_HIGHLIGHT_R = 0.0
-- 	BORDER_COLOR_CUSTOM_HIGHLIGHT_G = 0.61
-- 	BORDER_COLOR_CUSTOM_HIGHLIGHT_B = 0.75
-- 	BORDER_COLOR_CUSTOM_HIGHLIGHT_A = 1.0

-- 	BORDER_COLOR_CUSTOM_COUNTRY_HIGHLIGHT_R = 1.0
-- 	BORDER_COLOR_CUSTOM_COUNTRY_HIGHLIGHT_G = 0.0
-- 	BORDER_COLOR_CUSTOM_COUNTRY_HIGHLIGHT_B = 0.0
-- 	BORDER_COLOR_CUSTOM_COUNTRY_HIGHLIGHT_A = 1.0

-- 	BORDER_COLOR_TAP_SUCCESS_R = 0.0
-- 	BORDER_COLOR_TAP_SUCCESS_G = 0.61
-- 	BORDER_COLOR_TAP_SUCCESS_B = 0.75
-- 	BORDER_COLOR_TAP_SUCCESS_A = 1.0

-- 	BORDER_COLOR_TAP_FAIL_R = 0.8
-- 	BORDER_COLOR_TAP_FAIL_G = 0.0
-- 	BORDER_COLOR_TAP_FAIL_B = 0.0
-- 	BORDER_COLOR_TAP_FAIL_A = 0.8

-- 	BORDER_COLOR_TAP_NEUTRAL_R = 0.8
-- 	BORDER_COLOR_TAP_NEUTRAL_G = 0.8
-- 	BORDER_COLOR_TAP_NEUTRAL_B = 0.0
-- 	BORDER_COLOR_TAP_NEUTRAL_A = 0.8

-- 	BORDER_COLOR_RIVER_R = 0.0
-- 	BORDER_COLOR_RIVER_G = 0.1
-- 	BORDER_COLOR_RIVER_B = 0.8
-- 	BORDER_COLOR_RIVER_A = 1.0

-- 	BORDER_COLOR_CUSTOM_TEMP_HIGHLIGHT_R = 0.61 --for find province
-- 	BORDER_COLOR_CUSTOM_TEMP_HIGHLIGHT_G = 0.0
-- 	BORDER_COLOR_CUSTOM_TEMP_HIGHLIGHT_B = 0.75
-- 	BORDER_COLOR_CUSTOM_TEMP_HIGHLIGHT_A = 1.0

-- 	DRAW_REFRACTIONS_CUTOFF = 250
-- 	DRAW_SHADOWS_CUTOFF = 500
-- 	AGGRESSIVE_EXPANSION_RED_R = 1.0
-- 	AGGRESSIVE_EXPANSION_RED_G = 0.2
-- 	AGGRESSIVE_EXPANSION_RED_B = 0.0
-- 	AGGRESSIVE_EXPANSION_RED_A = 1.0
-- 	AGGRESSIVE_EXPANSION_AMBER_R = 1.0
-- 	AGGRESSIVE_EXPANSION_AMBER_G = 0.95
-- 	AGGRESSIVE_EXPANSION_AMBER_B = 0.0
-- 	AGGRESSIVE_EXPANSION_AMBER_A = 1.0
-- 	AGGRESSIVE_EXPANSION_GREEN_R = 0.0
-- 	AGGRESSIVE_EXPANSION_GREEN_G = 0.95
-- 	AGGRESSIVE_EXPANSION_GREEN_B = 0.0
-- 	AGGRESSIVE_EXPANSION_GREEN_A = 1.0
-- 	AG_FOR_MAX_COLOR_IN_COALITION_MAPMODE = 150
-- 	TRUCE_LENGTH_MIN_R = 1.0
-- 	TRUCE_LENGTH_MIN_G = 0.75
-- 	TRUCE_LENGTH_MIN_B = 0.0
-- 	TRUCE_LENGTH_MAX_R = 1.0
-- 	TRUCE_LENGTH_MAX_G = 0.0
-- 	TRUCE_LENGTH_MAX_B = 0.0
-- 	TRUCE_LENGTH_A = 1.0
-- 	MAX_NUM_YEAR_OF_TRUCE_FOR_MAPMODE = 15
-- 	COLONIAL_COLOR_INTERPOLATION_FACTOR = 0.35

-- 	MINIMAP_LAND_COLOR_R 			= 2
-- 	MINIMAP_LAND_COLOR_G 			= 15
-- 	MINIMAP_LAND_COLOR_B 			= 0
-- 	MINIMAP_LAND_COLOR_BASE_LERP 	= 0.4
-- 	MINIMAP_WATER_COLOR_R 			= 38
-- 	MINIMAP_WATER_COLOR_G 			= 124
-- 	MINIMAP_WATER_COLOR_B 			= 200
-- 	MINIMAP_PLAYER_COLOR_R			= 90
-- 	MINIMAP_PLAYER_COLOR_G			= 190
-- 	MINIMAP_PLAYER_COLOR_B			= 0
-- 	MINIMAP_FRIENDLY_COLOR_R		= 0
-- 	MINIMAP_FRIENDLY_COLOR_G		= 180
-- 	MINIMAP_FRIENDLY_COLOR_B		= 255
-- 	MINIMAP_ENEMY_COLOR_R			= 255
-- 	MINIMAP_ENEMY_COLOR_G			= 0
-- 	MINIMAP_ENEMY_COLOR_B			= 0
-- 	MINIMAP_UNIT_COLOR_BASE_LERP	= 0.4
-- 	MINIMAP_WATER_COLOR_BASE_LERP 	= 0.3

-- 	MAPMODE_EMPIRE_PROVINCE_FOR_EMPEROR_R = 0.5
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_EMPEROR_G = 0.0
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_EMPEROR_B = 0.3
	
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_ELECTOR_R = 0.6
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_ELECTOR_G = 0.2
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_ELECTOR_B = 0.0
	
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_FREE_CITY_R = 0.0
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_FREE_CITY_G = 0.0
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_FREE_CITY_B = 0.6
	
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_DEFAULT_R = 0.0
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_DEFAULT_G = 0.5
-- 	MAPMODE_EMPIRE_PROVINCE_FOR_DEFAULT_B = 0.0
	
-- 	MAPMODE_RELIGIOUS_LEAGUE_RELIGION_R = 0.0
-- 	MAPMODE_RELIGIOUS_LEAGUE_RELIGION_G = 0.5
-- 	MAPMODE_RELIGIOUS_LEAGUE_RELIGION_G = 0.5
-- 	MAPMODE_RELIGIOUS_LEAGUE_RELIGION_B = 0.0

-- 	MAPMODE_RELIGIOUS_LEAGUE_HERETIC_RELIGION_R = 0.0
-- 	MAPMODE_RELIGIOUS_LEAGUE_HERETIC_RELIGION_G = 0.0
-- 	MAPMODE_RELIGIOUS_LEAGUE_HERETIC_RELIGION_B = 0.5

-- 	MAPMODE_RELIGIOUS_LEAGUE_RELIGION_LEADER_R = 0.2
-- 	MAPMODE_RELIGIOUS_LEAGUE_RELIGION_LEADER_G = 0.7
-- 	MAPMODE_RELIGIOUS_LEAGUE_RELIGION_LEADER_B = 0.2

-- 	MAPMODE_RELIGIOUS_LEAGUE_HERETIC_RELIGION_LEADER_R = 0.2
-- 	MAPMODE_RELIGIOUS_LEAGUE_HERETIC_RELIGION_LEADER_G = 0.2
-- 	MAPMODE_RELIGIOUS_LEAGUE_HERETIC_RELIGION_LEADER_B = 0.7

-- 	MAPMODE_PERPETUAL_DIET_LOCATION_R = 0.2
-- 	MAPMODE_PERPETUAL_DIET_LOCATION_G = 0.8
-- 	MAPMODE_PERPETUAL_DIET_LOCATION_B = 0.8
	
-- 	MAX_TRADE_NODE_FLAGS_SHOWN = 5					-- -1 is unlimited
-- 	SHOW_TRADE_MODIFIERS_IN_TRADE_MAP_MODE = 1		-- 1 = true 0 = false
-- 	END_OF_COMBAT_GFX = 1
-- 	MAX_MAPMODE_COLOR_UPDATE_DELAY_MS = 200

-- 	MAX_ARMY_SPRITE_LEVEL_IN_NATION_DESIGNER = 4
