-- NGui = {

-- 	PROVINCE_FOCUS_ZOOM_HEIGHT = 0.25

-- 	MACRO_BUILD_FOCUS_ZOOM_HEIGHT = 0.149
-- 	MACRO_BUILD_BIG_SMALL_HEIGHT = 0.15
-- 	DELAY_ACCEPT_EVENT = 0.5 				-- Seconds. Disables event option buttons for the duration if > 0
-- 	DELAY_ACCEPT_CALL_TO_ARMS = 0.5		-- Seconds. Disables Call to Arms accept button for the duration if > 0
-- 	AUTO_SELECT_EVENT_MONTHS = 4
-- 	LEDGER_GUI_OBJECT_OFFSET = -5
-- 	LEDGER_RIGHT_ALIGNED_COLUMN_PADDING = 20
-- 	CELESTIAL_EMPIRE_VIEW_MAX_LINES = 4
-- 	DECISION_COLOR_R = 60
-- 	DECISION_COLOR_G = 117
-- 	DECISION_COLOR_B = 165
-- 	MAJOR_DECISION_COLOR_R = 146
-- 	MAJOR_DECISION_COLOR_G = 174
-- 	MAJOR_DECISION_COLOR_B = 114
-- 	PARLIAMENT_SEAT_COLOR_R = 60
-- 	PARLIAMENT_SEAT_COLOR_G = 117
-- 	PARLIAMENT_SEAT_COLOR_B = 165
-- 	PARLIAMENT_DEBATE_COLOR_R = 60
-- 	PARLIAMENT_DEBATE_COLOR_G = 117
-- 	PARLIAMENT_DEBATE_COLOR_B = 165
-- 	MAX_WAR_PARTICIPANTS_IN_TOOLTIPS = 40

-- }
